receivers:
  otlp/trace:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14317
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp:
    endpoint: "http://prometheus-platform:9090/api/v1/otlp"
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: http://prometheus-platform:9090/api/v1/write
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:
    timeout: 10s

  transform/promote_resource_attrs:
    error_mode: ignore
    metric_statements:
      - set(datapoint.attributes["service.instance.id"], resource.attributes["service.instance.id"]) where resource.attributes["service.instance.id"] != nil
      - set(datapoint.attributes["service.name"], resource.attributes["service.name"]) where resource.attributes["service.name"] != nil
      - set(datapoint.attributes["service.namespace"], resource.attributes["service.namespace"]) where resource.attributes["service.namespace"] != nil
      - set(datapoint.attributes["service.version"], resource.attributes["service.version"]) where resource.attributes["service.version"] != nil
      - set(datapoint.attributes["host.name"], resource.attributes["host.name"]) where resource.attributes["host.name"] != nil
      - set(datapoint.attributes["host.id"], resource.attributes["host.id"]) where resource.attributes["host.id"] != nil


  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  
  metricstransform:
    transforms:
      - include: ^traces_service_graph(.*)$
        match_type: regexp
        action: update
        new_name: iyzitrace_service_graph$$1
      - include: ^traces\.span\.metrics\.(.*)$
        match_type: regexp
        action: update
        new_name: iyzitrace.span.metrics.$$1
  
service:
  pipelines:
    metrics/otlp:
      receivers: [otlp/trace]
      processors: [batch, memory_limiter, metricstransform, transform/promote_resource_attrs]
      exporters: [otlphttp]
    metrics/prometheus:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheusremotewrite]
