receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: tempo-platform:4317
    tls:
      insecure: true
  otlp/metric:
    endpoint: metric-otel-enrichment:14317
    tls:
      insecure: true
  debug:
    verbosity: detailed

processors:
  batch:
    timeout: 10s

  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25

  transform/type_classifier:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(attributes["type"], "unknown") where attributes["type"] == nil
          - set(attributes["type"], "http") 
            where attributes["type"] == "unknown" and (attributes["http.method"] != nil or attributes["http.request.method"] != nil or attributes["http.url"] != nil or attributes["http.protocol"] != nil)
          - set(attributes["type"], "messaging")
            where (
              attributes["messaging.system"] != nil or
              attributes["messaging.destination.name"] != nil
            ) and attributes["type"] == "unknown"
          - set(attributes["type"], "cache")
            where (
              attributes["db.system"] != nil and attributes["db.system"] == "redis"
            ) and attributes["type"] == "unknown"
          - set(attributes["type"], "database")
            where (
              attributes["db.system"] != nil or
              attributes["db.namespace"] != nil or
              attributes["db.operation.name"] != nil or
              attributes["db.operation"] != nil
            ) and attributes["type"] == "unknown"
          - set(attributes["type"], "rpc")
            where (
              attributes["rpc.system"] != nil or
              attributes["rpc.service"] != nil or
              attributes["rpc.method"] != nil
            ) and attributes["type"] == "unknown"

  transform/span:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(span.attributes["operation.name"], span.name)
          - set(span.attributes["host.name"], resource.attributes["host.name"]) where resource.attributes["host.name"] != nil

connectors:
  spanmetrics:
    exemplars:
      enabled: true
    resource_metrics_cache_size: 1600
    dimensions:
      - name: type
      - name: host.name
      - name: http.method
      - name: http.url
      - name: net.host.port
    events:
      enabled: true
      dimensions:
        - name: exception.type
        - name: exception.message
    metrics_flush_interval: 10s
  servicegraph:
    metrics_flush_interval: 10s
    dimensions:
      - db.system
      - db.name
      - operation.name
      - type
      - host.name
    virtual_node_peer_attributes:
      - db.system
      - peer.service
    virtual_node_extra_label: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, transform/type_classifier, transform/span, batch]
      exporters: [debug, otlp, spanmetrics, servicegraph]
    metrics:
      receivers: [spanmetrics, servicegraph]
      processors: [memory_limiter, batch]
      exporters: [otlp/metric]