# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

exporters:
  # Tempo exporter for traces
  otlphttp/tempo:
    endpoint: "http://tempo:4318"
    tls:
      insecure: true
  
  otlphttp/loki:
    endpoint: http://loki:3100/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, batch]
      exporters: [otlp, otlphttp/tempo, debug, spanmetrics]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, batch]
      exporters: [opensearch, otlphttp/loki, debug]